// migrate-turso.ts — applies migration SQL to the Turso production database.
//
// WHY THIS SCRIPT EXISTS:
//   `prisma migrate deploy` validates that the datasource URL starts with "file:"
//   when the schema uses provider = "sqlite". It cannot connect to a libsql://
//   URL even though Turso is SQLite-compatible. The driver adapter in client.ts
//   handles that gap for runtime queries, but the Prisma migration engine has a
//   separate code path that doesn't use the adapter.
//
//   This script bypasses the migration engine: it reads the raw SQL file that
//   `prisma migrate dev` generated and sends it straight to Turso via @libsql/client.
//
// HOW TO RUN (once, before first deployment):
//   cd packages/db && pnpm exec tsx src/migrate-turso.ts
//   Then seed: pnpm exec prisma db seed
//
// SAFE TO RE-RUN:
//   Every CREATE TABLE uses "IF NOT EXISTS" — running twice is a no-op.

// Load packages/db/.env into process.env BEFORE reading DATABASE_URL.
// tsx (unlike `prisma` CLI) does not auto-load .env files, so we do it here.
// dotenv only sets variables that are NOT already set — it won't override
// a DATABASE_URL you export in your shell before running this script.
import "dotenv/config";

import { createClient } from "@libsql/client";
import { readFileSync }  from "node:fs";
import { resolve }       from "node:path";

async function main() {
  // ── Validate environment ────────────────────────────────────────────────────
  const url = process.env.DATABASE_URL ?? "";

  if (!url.startsWith("libsql://")) {
    console.error(
      "❌  DATABASE_URL must be a libsql:// URL.\n" +
      "    Make sure packages/db/.env has DATABASE_URL set to your Turso URL."
    );
    process.exit(1);
  }

  // ── Read the migration SQL ──────────────────────────────────────────────────
  // The migration file was generated by `prisma migrate dev` during local dev.
  // It contains plain SQLite-compatible CREATE TABLE and CREATE UNIQUE INDEX statements.
  const migrationPath = resolve(
    __dirname,
    "../prisma/migrations/20240101000000_init/migration.sql"
  );

  // Add "IF NOT EXISTS" to every CREATE TABLE so the script is idempotent.
  // Without it, a second run would fail with "table already exists".
  const sql = readFileSync(migrationPath, "utf-8").replace(
    /CREATE TABLE "/g,
    'CREATE TABLE IF NOT EXISTS "'
  );

  // ── Connect and execute ─────────────────────────────────────────────────────
  const client = createClient({ url });

  console.log("🔌  Connecting to Turso...");
  // Log only the hostname — never log the auth token.
  console.log(`    ${url.split("?")[0]}\n`);

  // executeMultiple sends the entire SQL string to Turso in one request.
  // Turso splits it into individual statements server-side and runs them in order.
  await client.executeMultiple(sql);

  console.log("✅  Migration applied successfully.");
  console.log("    Next step: seed the database —");
  console.log("    pnpm exec prisma db seed\n");

  client.close();
}

main().catch((err) => {
  console.error("❌  Migration failed:", err);
  process.exit(1);
});
